# POST http://localhost:5000/drugs
# Content-Type: application/json

# {
#     "name": "paracetamol",
#     "img": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftajgenerics.com%2Fwp-content%2Fuploads%2FParacetamol-Tablets-500-mg-Taj-Pharma.jpg&f=1&nofb=1&ipt=a8c3b1df0bd792526ce59d20356f82c72b4d789cf8c0f1c2ac4afb561d1032be&ipo=images",
#     "composition": "paracetamol",
#     "form": "tablet",
#     "category": "antipiretik",
#     "indication": "demam",
#     "dose": "500mg 3x 1",
#     "contraindication": "liver failure",
#     "manufacturer": ["GSK"],
#     "pregnancyCategory": "B",
#     "lactationSafety": "not safe"
# }

# POST http://localhost:5050/admin/register
# Content-Type: application/json

# {
#     "username": "testman3",
#     "email": "testman3@gmail.com",
#     "password": "testpassword"
# }

POST http://localhost:5050/admin/login
Content-Type: application/json

{
    "username": "testman3",
    "password": "testpassword"
}